// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNR5qeo9uzjot5nh7ZSLiit7bjdbbb5nY',
    appId: '1:90269352050:web:252c87995d2d29a9a8c2eb',
    messagingSenderId: '90269352050',
    projectId: 'espeon-a41a2',
    authDomain: 'espeon-a41a2.firebaseapp.com',
    storageBucket: 'espeon-a41a2.firebasestorage.app',
    measurementId: 'G-N3SL8JCCQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmBYW_FN6x89BlYP1tRK3zk4QorYHp--A',
    appId: '1:90269352050:android:9fce0d4be19f037ba8c2eb',
    messagingSenderId: '90269352050',
    projectId: 'espeon-a41a2',
    storageBucket: 'espeon-a41a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxiJlRUznCXDdUIErrxavzRR2S8BTWEw',
    appId: '1:90269352050:ios:da6b54a36a9ad5bea8c2eb',
    messagingSenderId: '90269352050',
    projectId: 'espeon-a41a2',
    storageBucket: 'espeon-a41a2.firebasestorage.app',
    iosClientId: '90269352050-9g1q4rqde11bqooqk81nkqdker3b4100.apps.googleusercontent.com',
    iosBundleId: 'com.dobby.espeon',
  );
}
